---
# Top level playbook for gts Core
# This is more complicated than MAP, since production and test are two sets of servers
# For MAP, prod and test are both td-tac01
# Option 1 --
#   Include all nodes, and use conditional to run tasks only on hosts of the requested env.
#   Downside is that ansible will have to loop through all nodes. Kind of wasteful
# Option 2--
#   Define a local host, and set env in local host. Then for the actual gts task, set hosts to that env variable

- hosts: localhost
  gather_facts: False
  tasks:
    - name: Is it pat test core nodes?
      set_fact:
        target_env: "pat_linux"
      when: "'pat' == env"
    
    - name: Is it bdt test core nodes?
      set_fact:
        target_env: "bdt"
      when: "'bdt' == env"

    - name: Is it oat test core nodes?
      set_fact:
        target_env: "oat_linux"
      when: "'oat' == env"

    - name: Is it all test core nodes?
      set_fact:
        target_env: "core_nodes_in_test"
      when: "'all' == env"

- hosts: "{{hostvars.localhost.target_env}}"
  gather_facts: False
  tasks:
    - command: hostname
      changed_when: False
