---
# Top level playbook for map admin
# input variable:
# prefix=[container prefix]
# todo=[recovery|status]

- include: playbooks/proxy.yml

- hosts: map_docker
  gather_facts: False
  roles:
    - role: map
      runto: "admin"