---
- hosts: td-pat201.test.ise.com
  gather_facts: False
  tasks:
     - name: Test out gtsenv module
       gtsenv: env_number=038 command='echo "gtsstatus -m" | opcon -s'

     - gtsenv: env_number=038 command="gtsCtrl status" 
