---
- hosts: map_docker
  gather_facts: False
  tasks:
    - name: Stopping MAP related containers
      command: chdir=/home/core/tacstack ~/bin/docker-compose -f docker-compose-prod.yml stop
      changed_when: False

    - wait_for: port=80 state=drained

    - pause: 
        seconds=30
        prompt="Wait for 30 seconds before restarting map to avoid httpd startup issue"

- include: playbooks/map_recovery.yml